
import React from 'react';
import { Link } from 'react-router-dom';
import Layout from '../components/Layout';

interface LandingPageProps {
  isAdmin?: boolean;
}

const LandingPage: React.FC<LandingPageProps> = ({ isAdmin }) => {
  return (
    <Layout isAdminAuthenticated={isAdmin}>
      <div className="flex flex-col items-center text-center py-16 gap-8">
        <div className="space-y-4 max-w-3xl">
          <div className="inline-flex items-center px-4 py-2 bg-indigo-50 text-indigo-700 rounded-full text-sm font-bold border border-indigo-100 mb-4 animate-fade-in">
             Next-Gen Biometric Identity Protection
          </div>
          <h1 className="text-5xl md:text-6xl font-black text-[#1e1b4b] tracking-tight leading-tight">
            Verify Humans. <br />
            <span className="text-indigo-600">Eliminate Fraud.</span>
          </h1>
          <p className="text-xl text-[#1e1b4b] leading-relaxed max-w-2xl mx-auto font-bold opacity-80">
            A frictionless verification engine combining behavioral biometrics, face recognition, and generative AI to secure your platform.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-4">
          <Link to="/auth" className="px-8 py-4 bg-indigo-600 text-white font-black rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 active:scale-95 transition-all text-lg flex items-center justify-center">
            Start Verification
          </Link>
          {isAdmin ? (
             <Link to="/admin" className="px-8 py-4 bg-white text-[#1e1b4b] font-black rounded-xl border border-slate-200 hover:border-indigo-600 hover:text-indigo-600 active:scale-95 transition-all text-lg flex items-center justify-center">
                Admin Console
             </Link>
          ) : (
            <Link to="/auth" className="px-8 py-4 bg-white text-[#1e1b4b] font-black rounded-xl border border-slate-200 hover:border-indigo-600 hover:text-indigo-600 active:scale-95 transition-all text-lg flex items-center justify-center">
                User Portal
            </Link>
          )}
        </div>

        <div className="mt-16 w-full max-w-5xl">
          <div className="bg-white p-2 rounded-[2.5rem] shadow-2xl border border-slate-100 overflow-hidden transform hover:scale-[1.01] transition-transform duration-500">
             <img src="https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1200&h=600" alt="Biometric Identity Mesh" className="rounded-[2rem] w-full object-cover aspect-video" />
          </div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-24 text-left">
          {[
            {
              bg: 'bg-blue-100', text: 'text-blue-600', title: 'Face Recognition',
              desc: 'Advanced Liveness detection using high-resolution camera analysis to prevent deepfakes.',
              icon: (
                <>
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </>
              )
            },
            {
              bg: 'bg-emerald-100', text: 'text-emerald-600', title: 'Behavioral Insights',
              desc: 'Patented analysis of user interaction patterns, timing, and logical reasoning accuracy.',
              icon: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            },
            {
              bg: 'bg-amber-100', text: 'text-amber-600', title: 'Identity Scores',
              desc: 'Consolidated trust profiles generated by our proprietary AI engine for instant decisioning.',
              icon: <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04M12 21.355l-.343-.133a11.944 11.944 0 01-6.234-5.23L12 11.23l6.577 4.762a11.944 11.944 0 01-6.234 5.23L12 21.355z" />
            }
          ].map((feature, i) => (
            <div key={i} className="p-6 bg-white rounded-2xl border border-slate-100 hover:shadow-md transition-shadow group">
              <div className={`w-12 h-12 ${feature.bg} ${feature.text} rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  {feature.icon}
                </svg>
              </div>
              <h3 className="text-lg font-black mb-2 text-[#1e1b4b]">{feature.title}</h3>
              <p className="text-[#1e1b4b] opacity-70 text-sm font-bold">{feature.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export default LandingPage;
